### DISCUSSION TITLE
Support for networks in compose files

### DISCUSSION THREAD

**Discussion by mkiael** [containerd/nerdctl#1040] [Q&A] [answered]
There seems to be limited support for the different options that can be specified for networks in a compose file, for example driver, driver_opts etc. I encountered this while trying to set up a macvlan network in my compose file:
```
networks:
  mvlan:
    name: my_mvlan
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: "100.98.76.0/24"
          gateway: "100.98.76.1"
          ip_range: "100.98.76.0/24"

```

Are there any ongoing work or discussions regarding extending the support for networks in compose files?
If not, would it be appropriate to open an issue for this?
