### DISCUSSION TITLE
Specifying entrypoint with multiple strings [...] is not supported yet

### DISCUSSION THREAD

**Discussion by jmperez81** [containerd/nerdctl#1069] [Q&A] [answered]
Hello everyone, some time ago I replaced docker with nerdctl (version 0.17.0) + containerd, and I really like it. However, for some docker-compose files I have been using I am facing the problem below:

`$ nerdctl compose -f docker-compose.yml up`

```
INFO[0000] Creating network container_default
FATA[0000] service karapace-registry: specifying entrypoint with multiple strings ([/bin/bash /opt/karapace/start.sh registry]) is not supported yet
FATA[0000] exit status 1
```
 
As the error message states, the docker-compose file is including this:

```
 ...
 karapace-registry:
     image: ghcr.io/aiven/karapace:develop
     entrypoint:
       - /bin/bash
       - /opt/karapace/start.sh
       - registry
 ...
```

which seems to be not supported. So questions from my side:

- Anyone can clarify when will this be supported? I could not find any information about it
- Any advice on what is the easiest way to overcome the problem? 

My knowledge about Dockerfiles is limited, I am following the getting started tutorial from an open-source tool. 

That tutorial is using docker and includes this docker-compose file. Although not ideal, I guess it's possible for me to rebuild the docker images modifying the entrypoint to include only one string...

Any help is appreciated.

Thanks in advance!
