### DISCUSSION TITLE
How to integrate with pre-commit?

### DISCUSSION THREAD

**Discussion by dudicoco** [containerd/nerdctl#1238] [Q&A]
Hi,

I have an alias for `docker="nerdctl"` in my bash profile.
When using pre-commit with a docker image hook I get an error:
```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
```

I assume pre-commit is not using the alias, is there a way to make pre-commit use an alias for the docker command?

**Comment by fahedouch** [comment]
looks like out of `nerdctl` scope!  but to help you debug this how can we reproduce this error ?

**Reply by dudicoco** [reply]
@fahedouch to reproduce, create `.pre-commit-config.yaml` with the following contents:
```yaml
repos:
- repo: local
  hooks:
  - id: hadolint
    name: Lint Dockerfiles
    language: docker_image
    entry: hadolint/hadolint:v2.10.0
    args:
    - hadolint
```

Then run the following:
```sh
pre-commit install
git add .
pre-commit run -a
```
