### DISCUSSION TITLE
nerdctl in containerd, `unable to start container process: error during container init: error mounting "/var/lib/nerdctl/NNN/containers/default/NNN/resolv.conf" to rootfs at "/etc/resolv.conf": ... no such file or directory: unknown

### DISCUSSION THREAD

**Discussion by nicolasespiau** [containerd/nerdctl#1243] [Q&A]
Hey folks,

I need some help with an issue running nerdctl commands inside a gitlab runner deployed on kubernetes with containerd runtime.

From the beginning I only have one FATAL error which is `level=fatal msg="no such file or directory"` when running a `nerdctl compose up` but also `nerd run hello-world`

Thanks to @AkihiroSuda's guidance I've entered the runner pod and tried some debug-full command:
```bash
nerdctl --debug-full run hello-world
```
Which gave me:
```bash
DEBU[0000] failed to run [aa-exec -p nerdctl-default -- true]: "[38] aa-exec: ERROR: profile 'nerdctl-default' does not exist\n"  error="exit status 1"
DEBU[0000] verification process skipped                 
DEBU[0000] final cOpts is [0xb60420 0xfa47c0 0xb60840 0xb605a0 0xb602a0 0xfa5e40 0xfa71c0 0xb60d80] 
FATA[0000] failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/nerdctl/1935db59/containers/default/767aa2c2a216d8fce638c59234f87c251f88c88311b3f82d5bcf4dc37fdf0dbb/resolv.conf" to rootfs at "/etc/resolv.conf": stat /var/lib/nerdctl/1935db59/containers/default/767aa2c2a216d8fce638c59234f87c251f88c88311b3f82d5bcf4dc37fdf0dbb/resolv.conf: no such file or directory: unknown
```

I get that DEBU message can be ignored.

But the thing is, focusing on the FATA message, if I perform `ls` or `stat` myself I can find the supposed missing file:
```bash
root@runner-btbzx--project-25793245-concurrent-07qhsp:/# stat /var/lib/nerdctl/1935db59/containers/default/767aa2c2a216d8fce638c59234f87c251f88c88311b3f82d5bcf4dc37fdf0dbb/resolv.conf
  File: /var/lib/nerdctl/1935db59/containers/default/767aa2c2a216d8fce638c59234f87c251f88c88311b3f82d5bcf4dc37fdf0dbb/resolv.conf
  Size: 120             Blocks: 8          IO Block: 4096   regular file
Device: 10301h/66305d   Inode: 5133481     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-07-16 21:59:50.226552351 +0000
Modify: 2022-07-16 21:59:50.226552351 +0000
Change: 2022-07-16 21:59:50.226552351 +0000
 Birth: 2022-07-16 21:59:50.226552351 +0000
 ```
```bash
root@runner-btbzx--project-25793245-concurrent-07qhsp:/# ls -l /var/lib/nerdctl/1935db59/containers/default/767aa2c2a216d8fce638c59234f87c251f88c88311b3f82d5bcf4dc37fdf0dbb
total 8
-rw-r--r-- 1 root root  13 Jul 16 21:59 hostname
-rw-r--r-- 1 root root 120 Jul 16 21:59 resolv.conf
```

So why is the `resolv.conf` considered missing while it's actually here?

Here is my nerdctl info:
```yaml
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.6
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file
  Storage: aufs native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-1017-aws
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.687GiB
 Name: runner-btbzx--project-25793245-concurrent-07qhsp
 ID: d4341431-1b20-4fc6-b55e-89dd1d3edd57

WARNING: IPv4 forwarding is disabled
```
