### DISCUSSION TITLE
cannot access containerd socket "/run/containerd/containerd.sock": no such file or directory

### DISCUSSION THREAD

**Discussion by aishwaryabk** [containerd/nerdctl#2008] [Q&A]
I am trying to create a container inside a container using nerdctl command:

	root@69adc10b8807:/home/jenkins/workspace/# nerdctl version
	Client:
	 Version:       v0.8.0
	 Git commit:    d57846db4a90540bc41e4683cd1a9f1e9e99170a
	FATA[0000] cannot access containerd socket "/run/containerd/containerd.sock": no such file or directory

	root@69adc10b8807:/home/jenkins/workspace/# nerdctl run -it ubuntu
	FATA[0000] cannot access containerd socket "/run/containerd/containerd.sock": no such file or directory

	root@69adc10b8807:/home/jenkins/workspace/# ls /run/
	lock  utmp

	root@69adc10b8807:/home/jenkins/workspace/# find / -name containerd.sock
	root@69adc10b8807:/home/jenkins/workspace/#

The `/run/containerd/containerd.sock` is not present.

**Comment by AkihiroSuda** [comment]
`sudo systemctl enable --now containerd`

**Reply by aishwaryabk** [reply]
This command is run inside the container of `quay.io/powercloud/inbound-agent:4.10-3.2` image and so `sudo: systemctl: command not found`

**Comment by fahedouch** [comment]
You need more configuration. I believe that [this discussion ](https://github.com/containerd/nerdctl/discussions/1383) will help you

**Reply by aishwaryabk** [reply]
Hi @fahedouch, I tried following the doc (https://github.com/containerd/nerdctl/blob/main/docs/rootless.md).
I created a new user and tried installing containerd using the rootless approach.

	root@69adc10b8807:/home/jenkins/workspace/# su aish
	$  sudo /usr/local/bin/containerd-rootless-setuptool.sh install
	[sudo] password for aish:
	[ERROR] Refusing to install rootless containerd as the root user
	$ /usr/local/bin/containerd-rootless-setuptool.sh install
	[ERROR] Needs systemd (systemctl --user)
	$
	$ systemctl
	sh: 4: systemctl: not found

But this does not work. Is there any other approach for solving this? Or am I missing anything?

**Reply by fahedouch** [reply]
hi @aishwaryabk , Sorry but do not understand the relation between setting up a rootless environment  and the original issue to access containerd socket from the container

**Comment by itsCheithanya** [comment]
Getting the same error after I started appending the grub file and rebooted my system for setting up bpf lsm for some use case and this happend

`sudo vi /etc/default/grub
`
Append the following to the GRUB_CMDLINE_LINUX variable and save.
`GRUB_CMDLINE_LINUX="lsm=lockdown,capability,yama,apparmor,bpf"
`
`sudo update-grub
`
![image](https://github.com/containerd/nerdctl/assets/85927700/f9cc4e5e-a53d-4261-b112-6738f864ffe4)
![image](https://github.com/containerd/nerdctl/assets/85927700/fb2014ea-4b0b-474b-8dff-828de285ca82)
![image](https://github.com/containerd/nerdctl/assets/85927700/0bbfa69e-6cad-47cf-8c66-2d9991b0d5ac)
![image](https://github.com/containerd/nerdctl/assets/85927700/2dc5d480-09b7-48dd-a47f-c5b5fbcf9be6)

**Comment by huabowen001** [comment]
Specify the mount volume when building the container, rather than mounting it through an image of an existing mount volume
```
apiVersion: v1
kind: Pod
metadata:
  name: build-image
spec:
  containers:
  - name: build-image
    image: ubuntu:v1.0.0	
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
      - name: containerd-sock
        mountPath: /run/containerd/containerd.sock
  nodeSelector:
    kubernetes.io/hostname: cluster-worker
  restartPolicy: Always
  volumes:
    - name: containerd-sock
      hostPath:
        path: /run/containerd/containerd.sock
        type: Socket
```
