### DISCUSSION TITLE
Error while creating container: exit status 1

### DISCUSSION THREAD

**Discussion by Juxn89** [containerd/nerdctl#2010] [Q&A]
## Description
Whe run the command **nerdctl compose up -d** I got this error:
```FATA[0000] error while creating container **container_name**: exit status 1```

### docker-compose.yml
```
services:
  teslodb:
    image: mongo:5.0.0
    container_name: teslo-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
```
### Version
**nerdctl**: 1.0.0
