### DISCUSSION TITLE
Passing arguments to OCI runtime

### DISCUSSION THREAD

**Discussion by Wonderfall** [containerd/nerdctl#2146] [Q&A] [answered]
Hi, I'm trying out `nerdctl` since it has features I like. Unfortunately, I can't find a way to pass runtime arguments to gVisor, which is the OCI runtime I use for most of my workloads. With Docker it's quite easy, for instance in `daemon.json`:

```json
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc"
        },
        "runsc-kvm": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--platform=kvm"
            ]
        },
```

With containerd, something like that would work too:

```toml
version = 2
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc]
  runtime_type = "io.containerd.runsc.v1"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc.options]
    TypeUrl = "io.containerd.runsc.v1.options"
    ConfigPath = "/etc/containerd/runsc.toml"
```

```toml
# runsc.toml
[runsc_config]
platform = "kvm"
```

Alas, `nerdctl` does not support CRI plugins so these settings have no effect.

What would be the best approach to achieve that, or is that even possible? Thanks for the help. :)
