### DISCUSSION TITLE
Which containerd plugins can be safely disabled for a docker compatible workload?

### DISCUSSION THREAD

**Discussion by Jip-Hop** [containerd/nerdctl#2457] [Q&A]
Which plugins can I safely add to `disabled_plugins` in the containerd `config.toml`? I'm running containerd just for `nerdctl` and want to keep the docker compatible features working such as `nerdctl run` and `nerdctl compose`.

I have now disabled `cri` as I don't think I need it. Or does `nerdctl` need it?

```toml
version = 2
# cri is not used by nerdctl, or is it?
disabled_plugins = ["io.containerd.grpc.v1.cri"]
```

Which additional plugins can I add to the `disabled_plugins` list?
