### DISCUSSION TITLE
No log viewer type registered for logging driver "fluentd"

### DISCUSSION THREAD

**Discussion by viggnah** [containerd/nerdctl#3431] [Q&A]
Couldn't find any reference to this error anywhere else, not sure if I'm doing something completely wrong..

I'm using the following docker compose file - 
```yaml
version: '3.8'

services:
  wso2-apim:
    image: wso2/wso2am:4.3.0-rocky
    container_name: wso2-apim
    ports:
      - "8337:8337"
      - "8300:8300"
      - "9500:9500"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: wso2-apim
```

Getting the following error - 
```
wso2-apim |time="2024-09-16T14:05:53+05:30" level=fatal msg="no log viewer type registered for logging driver \"fluentd\""
INFO[0000] Container "wso2-apim" exited                 
INFO[0000] All the containers have exited  
```

Using Rancher Desktop `v1.15.1` which has nerdctl `v1.7.6` bundled. Running on macOS 14.4.1 (23E224), M1 chip.

Saw in the code that log viewers are only registered for `json-file`, `journald` and `cri`. Not sure if this is the actual problem??
https://github.com/containerd/nerdctl/blob/main/pkg/logging/log_viewer.go#L46
