### DISCUSSION TITLE
nerdctl compose start containers form different file, but container's network could not connect.

### DISCUSSION THREAD

**Discussion by luya0000** [containerd/nerdctl#898] [Show and tell]
On the one host, I use  docker-compose1.yaml  to starts a CentOS container and then uses docker-compose2.Yaml starts another  Nginx container. Nginx service cannot be accessed in CentOS container. Guess it's caused by the intranet segment. How to deal with it. 

docker-compose1.yaml  
```
version: '2.3'
services:
  centos:
    image: centos:7
    container_name: centos
    restart: always
    command: sleep 3600
```
```
docker-compose2.yaml 
version: '2.3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
```
In centos's container to telnet nginx service with host ip (eg: 192.168.2.100:80) ,can't connect.
