### ISSUE TITLE
[Compose] 

### ISSUE THREAD

**Issue by yqlbu** [containerd/nerdctl#1074]
### Description

Hi, I am experiencing an issue where I defined the `restart=always` param in the `docker-compose.yml`, but the container does not spin up at boot.

### Steps to reproduce the issue

1. Prepare a docker-compose.yml for the container

```yaml
version: "3.4"

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    networks:
      - proxy
    volumes:
      - /etc/uptime-kuma:/app/data
    ports:
      - 3001:3001

networks:
  proxy:
    name: proxy
```

2. Run `nerdctl compose up -d` to spin up the container

### Describe the results you received and expected

The container is able to spin up at its first launch with the `nerdctl compose up -d` command. However, when the machine is rebooted, the container stops and not able to spin up again.

I assume that `Nerdctl` inherits the generic feature of starting the container at boot if the `restart=always` param persists in the `docker-compose.yml`

### What version of nerdctl are you using?

0.17.0-beta.0
