### ISSUE TITLE
nerdctl compose file map multiple ports

### ISSUE THREAD

**Issue by charmingdog** [containerd/nerdctl#1144]
### What is the problem you're trying to solve

when compose.yml file include follows code will get error:
```
version: "3"
services:
  flit-accessor:
    image: flit-accessor:${FlitAccessorVersion}
    container_name: flit-accessor
    ports:
      - "22200-22299:22200-22299"

....
```

![image](https://user-images.githubusercontent.com/20454889/174519248-22b148a0-fdd7-4f8d-9dab-b14b71b7331f.png)

and this operation will cause ```~/.local/share/nerdctl/1935db59/names/default/flit-accessor ``` file ,which will cause the container to fail to be created later
![image](https://user-images.githubusercontent.com/20454889/174519635-328bb6e3-48bb-4ace-87d4-724c06fe017c.png)
![image](https://user-images.githubusercontent.com/20454889/174519688-39696705-c780-4576-9ee6-29fba663e085.png)

### Describe the solution you'd like

nerdctl compose file can map multiple ports and when compose failed can still create service

**Comment by fahedouch** [comment]
to unblock the situation you can remove `rm  /var/lib/nerdctl/1935db59/names/default/flit-accessor`

**Comment by fahedouch** [comment]
Fixed by https://github.com/containerd/nerdctl/pull/1151

**Comment by chawson** [comment]
### `compose.yaml`: service part
```yaml
mozi-zlm:
    image: nginx:1.27.4
    ports:
      - '32000-32200:32000-32200'
      - '32000-32200:32000-32200/udp'
```

### `nerdctl compose up -d` received

![Image](https://github.com/user-attachments/assets/269963c7-6f3f-4cad-846b-1a15fbb1b1a0)

![Image](https://github.com/user-attachments/assets/d4987dfe-3881-4552-b5a0-0c330dd5f546)

### `nerdctl version`
Client:
 Version:	v2.0.2
 OS/Arch:	linux/amd64
 Git commit:	1220ce7ec2701d485a9b1beeea63dae3da134fb5
 buildctl:
  Version:	v0.18.1
  GitCommit:	eb68885955169461d72dc2b7e6d084100fcaba86

### `nerdctl info`
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v2.0.1
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log:     fluentd journald json-file none syslog
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version:   6.14.0-061400rc5-generic
 Operating System: Linux Mint 22.1
 OSType:           linux
 Architecture:     x86_64
 CPUs:             6
 Total Memory:     15.54GiB
