### ISSUE TITLE
All services use the same network(external) but some service can't find the correct address of another address

### ISSUE THREAD

**Issue by charmingdog** [containerd/nerdctl#1149]
### Description

```~/.local/share/nerdctl/1935db59/etchosts/default/b3571ed508bb30a1598eb9f782ff49d134bccbe500dcbf34ef15bfd41641a743/hosts``` have multiple lines of the same service

![image](https://user-images.githubusercontent.com/20454889/174731091-56914ae0-8dff-4b9b-bcfe-8aaede267948.png)

and dns results for different services are different which cause ping error （The service can not use the correct ip）
![image](https://user-images.githubusercontent.com/20454889/174730555-b4e142c6-0a04-47ec-a2bb-1d8b776d5383.png)

the correct is ：
![image](https://user-images.githubusercontent.com/20454889/174730658-ed3f7b8f-fb12-4520-8d51-d8289c1373c5.png)

### Steps to reproduce the issue

I don't know how it happens 

### Describe the results you received and expected

All services use the same external network can communicate with each other。

### What version of nerdctl are you using?

nerdctl version 0.20.0

**Comment by Zheaoli** [comment]
Hello, would you mind to give us the compose file you use to reproduce this issue?

**Comment by charmingdog** [comment]
1. create network
   ```network  create  --subnet 10.5.2.0/24 --gateway 10.5.2.1 test```

2. create redis-1.yml and redis-2.yml

   - redis-1.yml

     ```
     version: "3"
     services:
       redis-1:
         image: redis:7.0.2
         container_name: redis-1
         command: ["redis-server","/usr/local/etc/redis/redis.conf"]
         ports:
           - "51710:6379"
         volumes:
           - /data/Dockerfile/test/conf-1:/usr/local/etc/redis
           - /data/Dockerfile/test/data-1:/data
         networks:
           test:
             aliases:
               - redis-1
     networks:
       test:
         external: true
     ```

   - redis-2.yml

     ```
     version: "3"
     services:
       redis-2:
         image: redis:7.0.2
         container_name: redis-2
         command: ["redis-server","/usr/local/etc/redis/redis.conf"]
         ports:
           - "51720:6379"
         volumes:
           - /data/Dockerfile/test/conf-2:/usr/local/etc/redis
           - /data/Dockerfile/test/data-2:/data
         networks:
           test:
             aliases:
               - redis-2
     networks:
       test:
         external: true
     ```

3.  start redis-1

   ```
   nerdctl compose -f redis-1 up -d
   ```

4. start redis-2 multiple

   ```
   nerdctl compose -f redis-2 up -d
   nerdctl compose -f redis-2 down 
   nerdctl compose -f redis-2 up -d
   nerdctl compose -f redis-2 down 
   nerdctl compose -f redis-2 up -d
   ```

5. ping on redis-1

   ```
   nerdctl exec -ti redis-1 bash
   > apt update
   > apt install iputils-ping
   > ping redis-2
   ```

 
![image](https://user-images.githubusercontent.com/20454889/174924918-5c9a9bf7-a686-4759-ae6c-327361764f3d.png)


6. check 

   ```
   nerdctl inspect redis-1
   ```

  
![image](https://user-images.githubusercontent.com/20454889/174924943-6737ce0b-1f96-4083-8f72-fa1ee852ae25.png)


   ```cat /home/saas/.local/share/nerdctl/1935db59/etchosts/default/66e72d84cccad33b476875dc85823a5eb6a4c5050fc25cd2ef2dbe476cc92ede/hosts```

   
![image](https://user-images.githubusercontent.com/20454889/174924970-25b54816-fb51-4d5d-bf69-dc280b3807b1.png)


7. check actual redis-2 ip
![image](https://user-images.githubusercontent.com/20454889/174925078-7901e803-aba7-4564-98e0-656ae12e9f3b.png)
