### ISSUE TITLE
Environment variable $HOME in docker-compose.yml is not expanded

### ISSUE THREAD

**Issue by AnqiPang** [containerd/nerdctl#1663]
### Description

Copy the issue from https://github.com/runfinch/finch/issues/124.
Environment variable $HOME in docker-compose.yml is not expanded.

### Steps to reproduce the issue

1. Create the docker-compose.yml below.
```
version: '3.7'
services:
  wordpress:
    image: wordpress:5.7
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ${HOME}/hello.txt:/root/hello.txt
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
  ```
2. Create a file to mount the volume.
```
echo $HOME
/Users/hieki

echo hello > ~/hello.txt
cat ~/hello.txt
hello
```
3. Run `lima nerdctl compose up` and it failed.
```
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]     
INFO[0000] Ensuring image wordpress:5.7                 
INFO[0000] Ensuring image mariadb:10.5                  
INFO[0000] Creating container finch_wordpress_1         
INFO[0000] Re-creating container finch_db_1             
FATA[0000] error while creating container finch_wordpress_1: exit status 1         
```
4. Modify docker-compose.yml and rewrite the files to mount to absolute paths. It works fine.
```
version: '3.7'
services:
  wordpress:
    image: wordpress:5.7
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - /Users/hieki/hello.txt:/root/hello.txt
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
```

### Describe the results you received and expected

 Environment variable $HOME in docker-compose.yml should be expanded.

### What version of nerdctl are you using?

```
Client:
 Version:	v1.1.0
 OS/Arch:	linux/amd64
 Git commit:	18944bc70784dfa83010d37054d75487a58ab581
 buildctl:
  Version:	v0.10.6
  GitCommit:	0c9b5aeb269c740650786ba77d882b0259415ec7

Server:
 containerd:
  Version:	v1.6.12
  GitCommit:	a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:	1.1.4
  GitCommit:	v1.1.4-0-g5fd4c4d1
  ```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Lima

### Host information

```
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.12
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs fuse-overlayfs stargz
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
  rootless
 Kernel Version: 5.19.0-26-generic
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.825GiB
 Name: lima-default
 ID: 12637925-c1a5-4574-beda-a33046b62651
 ```
