### ISSUE TITLE
how to debug `nerdctl compose up`

### ISSUE THREAD

**Issue by rkonfj** [containerd/nerdctl#1670]
### Description

get error `FATA[0000] error while creating container coredns: exit status 1` when using `nerdctl compose up`

### Steps to reproduce the issue

1. create a compose.yml like this:
```
services:
  nginx:
    image: nginx:1.23.2
    container_name: nginx
    restart: always
  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
    restart: always
    network_mode: "container:nginx"
```
2. run `nerdctl compose up -d` and get the error
```
INFO[0000] Ensuring image nginx:1.23.2
INFO[0000] Ensuring image coredns/coredns:1.10.0
INFO[0000] Creating container coredns
INFO[0000] Re-creating container nginx
FATA[0000] error while creating container coredns: exit status 1
```

### Describe the results you received and expected

without error

### What version of nerdctl are you using?

v1.1.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information
```
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.12
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.0-162.6.1.el9_1.0.1.x86_64
 Operating System: Rocky Linux 9.1 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 93.79GiB
 Name: headq
 ID: 4643dd54-7788-488d-a450-7468458b2f92

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
