### ISSUE TITLE
Nerdctl EKS cluster 1.24 with compose

### ISSUE THREAD

**Issue by tppalani** [containerd/nerdctl#2323]
### Description

Hi Team,

1) EKS cluster is running with version 1.24 master and managed node group.
2) Installed tekton pipeline inside EKS cluster and its up and running.
3) Created tekton task to run the docker compose yaml file with below contents.

```
version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14      
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: nginx
    volumes:
      - ./output/result:/usr/share/devops/test-output   
```

```
- name: grid
      image: docker.io/containerd-nerdctl
      workingDir: $(workspaces.source.path)/source
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      securityContext:
        allowPrivilegeEscalation: true
        runAsUser: 0
        privileged: true
      script: |
        #!/usr/bin/env bash
        set -xe
        ls -lrt
        /usr/local/bin/nerdctl compose up
  volumes:
    - name: varlibc
      emptyDir: {}
    - name: docker-socket
      hostPath:
        path: /run/containerd/containerd.sock
  workspaces:
    - name: source
```

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Tekton pipeline outout

```
+ ls -lrt
total 32
-rw-rw-r-- 1 root 1001 2690 Jun 22 15:17 pom.xml
-rw-rw-r-- 1 root 1001  408 Jun 22 15:17 [healthcheck.sh](http://healthcheck.sh/)
-rw-rw-r-- 1 root 1001  890 Jun 22 15:17 docker-compose.yaml
-rw-rw-r-- 1 root 1001  699 Jun 22 15:17 Dockerfile
drwxrwsr-x 4 root 1001 4096 Jun 22 15:17 src
drwxr-sr-x 9 root 1001 4096 Jun 22 15:20 target
+ /usr/local/bin/nerdctl compose up
time="2023-06-22T15:20:46Z" level=fatal msg="cannot access containerd socket \"/run/containerd/containerd.sock\": no such file or directory"
```

### What version of nerdctl are you using?

[root@ip-1.2.3.4 containerd]# /usr/local/bin/nerdctl version
WARN[0000] unable to determine buildctl version: exec: "buildctl": executable file not found in $PATH
Client:
 Version:       v1.4.0
 OS/Arch:       linux/amd64
 Git commit:    7e8114a82da342cdbec9a518c5c6a1cce58105e9
 buildctl:
  Version:

Server:
 containerd:
  Version:      1.6.19
  GitCommit:    1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:      1.1.4
  GitCommit:    5fd4c4d144137e991c4acebb2146ab1483a97925

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Others

### Host information

[root@ip-1-2-3-4 containerd]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
