### ISSUE TITLE
Сontainer logs on stdout `nerdctl compose up` stop printing after rotating the json log file

### ISSUE THREAD

**Issue by happwrap** [containerd/nerdctl#2903]
### What is the problem you're trying to solve

We have configured rotation of service log files in the compose file as follows:
```yaml
logging:
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "2"
```
When running `nerdctl compose up` container logs on stdout stop printing after rotating the json log file.

### Describe the solution you'd like

The problem is solved by replacing the `-f` argument with `-F` when calling the `tail` command:
[json_logger.go](https://github.com/containerd/nerdctl/blob/main/pkg/logging/json_logger.go)
```go
210	if lvopts.Follow {
211		args = append(args, "-F")
212	}
```

### Additional context

So we add the `--retry` argument to the `--follow` argument for the `tail` command.
