### ISSUE TITLE
Support for ephemeral host ports in compose

### ISSUE THREAD

**Issue by bforbis** [containerd/nerdctl#351]
Try running a compose where ports for a service are bound to an ephemeral port, as documented in https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

```
version: '3'
services:
  foo:
    build: .
    ports:
      - 3000
```

When starting this using `nerdctl compose up`, I receive an error:

```
FATA[0000] unsupported port number: 0
```
