### ISSUE TITLE
Accessing external drives from lima for nerdctl

### ISSUE THREAD

**Issue by greghao** [containerd/nerdctl#541]
As the subject notes, I am trying to access an external drive. Below is my docker-compose.yml for nerdctl:

`version: "3.7"`
`services:`
`  autoindex:`
`    container_name: autoindex`
`    image: dceoy/nginx-autoindex:latest`
`    restart: always`
`    security_opt:`
`      - no-new-privileges:true`
`    ports:`
`      - "8080:80"`
`    volumes:`
`      - /Volume/External:/var/lib/nginx/html:ro `

Any guidance would be greatly appreciated!

**Comment by AkihiroSuda** [comment]
You have to add following likes to `~/.lima/default/lima.yaml`

```
mounts:
  - location: "~"
    writable: false
  - location: "/tmp/lima"
    writable: true
  - location: "/Volume/External"
    writable: false
```

For further questions about Lima, please use https://github.com/lima-vm/lima/discussions
