### ISSUE TITLE
[Compose] support for running with container's network namespace 

### ISSUE THREAD

**Issue by sureshg** [containerd/nerdctl#549]
```
  app:
     ....
  tcpdump:
    image: nicolaka/netshoot:latest
    restart: always
    network_mode: "container:app"
    command: [ "tcpdump" ]
```
Running the above compose app throws the following error
`FATA[0000] unsupported network_mode: "container:app" ` 

Container networking is very useful for running debugging sidecars (eg: `tcpdump` or other networking tools)
