### ISSUE TITLE
Compose: support cosign

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#607]
Depends on:
- https://github.com/containerd/nerdctl/issues/611
- - -
Cosign support for `nerdctl pull` and `nerdctl push` is being added in #556 #606 (v0.15).

We should support cosign for `nerdctl compose` too.

Probably we should extend the Compose Spec with `x-nerdctl-` prefix. https://github.com/compose-spec/compose-spec/blob/master/spec.md#extension

YAML for verifying the image could be like this:
```yaml
services:
  foo:
    image: bar
    x-nerdctl-verify: cosign
    x-nerdctl-cosign-key: /path/to/cosign.pub
```

But I'm not sure how the YAML should look like for signing the images with `nerdctl compose push`, as we will have to have two different properties for prv key and pub key.

Maybe like this:

```yaml
services:
  foo:
    image: bar
    x-nerdctl-verify: cosign
    x-nerdctl-cosign-public-key: /path/to/cosign.pub
    x-nerdctl-sign: cosign
    x-nerdctl-cosign-private-key: /path/to/cosign.key
```

**Comment by AkihiroSuda** [comment]
cc @developer-guy @Dentrax @ktock

**Comment by fahedouch** [comment]
otherwise  we don't have to set the configuration in the docker-compose spec it can be supported by flags. sthg like `nerdctl compose pull --verify=cosign  --cosign-key=/path/to/key` may be very useful too

**Comment by AkihiroSuda** [comment]
> otherwise we don't have to set the configuration in the compose spec it can be supported by flags. sthg like `nerdctl compose pull --verify=cosign --cosign-key=/path/to/key` may be very useful too

No, because a single YAML may have references to images signed with different keys.

**Comment by developer-guy** [comment]
sounds amazing @AkihiroSuda 🤩 when do we start implementing this 🚀

**Comment by Dentrax** [comment]
> otherwise we don't have to set the configuration in the compose spec it can be supported by flags. sthg like `nerdctl compose pull --verify=cosign --cosign-key=/path/to/key` may be very useful too

Passing `--verify` and ` --cosign-key` flags would be a bit ambiguous from the UX perspective. It had better not to pass these flags, since what I understand here is like: "I signed an _alternate compose file_ and trying to verify it using cosign just before calling the `pull` command. If verification fails, skip the _pull_ operation."

If we really want to pass variables by using flags, we probably find a way out how should we _map_ the specified _key_ for each image as follows:

```
--verify=cosign --cosign-key=[IMAGE1:/path/to/key1] --cosign-key=[IMAGE2:/path/to/key2]
```

**Comment by fahedouch** [comment]
@AkihiroSuda  @Dentrax  
I do not really agree. When we do  `nerdctl compose pull --verify=cosign --cosign-key=/path/to/key` , we are aware that we are targeting all services in the specs : signing all images with same key
targeting specific service will be sthg like this : `nerdctl compose pull  service1 --verify=cosign --cosign-key=/path/to/key`.

**Comment by Junnplus** [comment]
> When we do nerdctl compose pull --verify=cosign --cosign-key=/path/to/key , we are aware that we are targeting all services in the specs : verifying all images with same key

I think in most cases, the signature keys of different images may be different, which cannot be controlled by the user.

Maybe we can map the specified key for different services.
`--verify=cosign --cosign-key=[SERVICE1:/path/to/key1] --cosign-key=[SERVICE2:/path/to/key2]`

**Comment by developer-guy** [comment]
kindly ping ✌️

**Comment by Zheaoli** [comment]
I think maybe we can follow the following design. 

```yaml
services:
  foo:
    image: bar
    x-nerdctl-verify: cosign
    x-nerdctl-cosign-key: /path/to/cosign.pub
  foo2:
    image: bar
    x-nerdctl-need-verify: true
codesign:
    x-nerdctl-cosign-key: /path/to/cosign.pub
```

People can spec a global cosign key and decide which image would be verified and override the global key or not.
