### ISSUE TITLE
invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by tyteen4a03** [containerd/nerdctl#760]
With a directory structure of:

```
- ~
-- UppercaseRepo
--- subdirectory
---- Dockerfile
--- docker-compose.yaml
```

docker-compose.yaml
```
version: "3"
# The dev docker-compose file
services:
  myservice:
    build: subdirectory
```

When running `nerdctl compose up -d` from `~/UppercaseRepo`, it will emit a fatal error: `invalid reference format: repository name must be lowercase`. If I rename the folder to `uppercaserepo`, or `nerdctl compose build`, the build succeeds. Docker Compose can handle cases like this without problems.

This is with nerdctl v0.16.0 on macOS 11.6.3 (Intel)
