### ISSUE TITLE
Compose ignores ipv4_address

### ISSUE THREAD

**Issue by ianbarker** [containerd/nerdctl#852]
When launching containers using `nerdctl compose` the containers are not respecting `ipv4_address` in the docker-compose.yml file.

####Steps to reproduce

docker-compose.yml

```
version: "3.9"

services:  
    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            devnet:
                ipv4_address: 172.20.0.12
                
networks:
  devnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
```

output

```
$ lima nerdctl inspect 7666e88d3723
[
    {
        "Id": "7666e88d3723e8828b7ec597338825aaae4286c5d14cefd68a264def8b468b6a",
        "Created": "2022-03-02T16:47:42.892354752Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "redis-server"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Pid": 242571,
            "ExitCode": 0,
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "docker.io/library/redis:latest",
        "ResolvConfPath": "/home/ianbarker.linux/.local/share/nerdctl/1935db59/containers/default/7666e88d3723e8828b7ec597338825aaae4286c5d14cefd68a264def8b468b6a/resolv.conf",
        "HostnamePath": "/home/ianbarker.linux/.local/share/nerdctl/1935db59/containers/default/7666e88d3723e8828b7ec597338825aaae4286c5d14cefd68a264def8b468b6a/hostname",
        "LogPath": "/home/ianbarker.linux/.local/share/nerdctl/1935db59/containers/default/7666e88d3723e8828b7ec597338825aaae4286c5d14cefd68a264def8b468b6a/7666e88d3723e8828b7ec597338825aaae4286c5d14cefd68a264def8b468b6a-json.log",
        "Name": "redis",
        "Driver": "fuse-overlayfs",
        "Platform": "linux",
        "AppArmorProfile": "nerdctl-default",
        "NetworkSettings": {
            "Ports": {
                "6379/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "6379"
                    }
                ]
            },
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.20.0.175",
            "IPPrefixLen": 16,
            "MacAddress": "7a:36:cf:ff:ec:7c",
            "Networks": {
                "unknown-eth0": {
                    "IPAddress": "172.20.0.175",
                    "IPPrefixLen": 16,
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "7a:36:cf:ff:ec:7c"
                }
            }
        }
    }
]
```

As you can see the container has an assigned IP of 172.20.0.175 instead of 172.20.0.12
