### ISSUE TITLE
Add mirror config support at nerdctl.yaml

### ISSUE THREAD

**Issue by saltbo** [containerd/nerdctl#981]
### What is the problem you're trying to solve

When I set the image mirror, I need to maintain many configs.  

```bash
➜  nerdctl tree
.
├── buildkit
│   └── buildkitd.toml
├── containerd
│   └── certs.d
│       ├── docker.io
│       │   └── hosts.toml
│       ├── gcr.io
│       │   └── hosts.toml
│       └── quay.io
│           └── hosts.toml
└── nerdctl.toml
```

### Describe the solution you'd like

Add mirror config support at nerdctl.yaml like the `registries.yaml` of k3s
```yaml
mirrors:
  "docker.io":
    endpoint:
      - "https://xxxx.mirror.aliyuncs.com"
      - "https://mirrors.example.com"
  "quay.io":
    endpoint:
      - "https://mirrors.example.com"
  "gcr.io":
    endpoint:
      - "https://mirrors.example.com"

```
